from .intra_contrastive_loss import  IntraPixelContrastLoss
from .inter_contrastive_loss import  InterPixelContrastLoss
from .double_contrastive_loss import  DoublePixelContrastLoss
from .double_contrastive_selfpace_loss import  SELFPACEDoublePixelContrastLoss
from .double_contrastive_selfpace_epoch_loss import  EPOCHSELFPACEDoublePixelContrastLoss
from .loss_build import criterion